#ccflags-y += -Wall -DADV_DEBIAN
ccflags-y += -DADV_DEBIAN
obj-y += ilitek.o
ilitek-y +=	ilitek_main.o \
	ilitek_platform_init.o \
	ilitek_update.o \
	ilitek_tool.o \
	ilitek_protocol.o \
	ilitek_mp.o
